// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: internal/infrastructure/proto/runner.proto

package runner

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Student       int32                  `protobuf:"varint,1,opt,name=student,proto3" json:"student,omitempty"`
	Problem       int32                  `protobuf:"varint,2,opt,name=problem,proto3" json:"problem,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Lang          string                 `protobuf:"bytes,4,opt,name=lang,proto3" json:"lang,omitempty"`
	Cases         []byte                 `protobuf:"bytes,5,opt,name=cases,proto3" json:"cases,omitempty"` //json string in format `[{"test_num": 0, "input": "..."}, ...]`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCodeRequest) Reset() {
	*x = RunCodeRequest{}
	mi := &file_internal_infrastructure_proto_runner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCodeRequest) ProtoMessage() {}

func (x *RunCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_proto_runner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCodeRequest.ProtoReflect.Descriptor instead.
func (*RunCodeRequest) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_proto_runner_proto_rawDescGZIP(), []int{0}
}

func (x *RunCodeRequest) GetStudent() int32 {
	if x != nil {
		return x.Student
	}
	return 0
}

func (x *RunCodeRequest) GetProblem() int32 {
	if x != nil {
		return x.Problem
	}
	return 0
}

func (x *RunCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RunCodeRequest) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *RunCodeRequest) GetCases() []byte {
	if x != nil {
		return x.Cases
	}
	return nil
}

type RunCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []byte                 `protobuf:"bytes,1,opt,name=results,proto3" json:"results,omitempty"` //json string in format `[{"test_num": 0, "input": "...", "output": "..."}, ...]`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCodeResponse) Reset() {
	*x = RunCodeResponse{}
	mi := &file_internal_infrastructure_proto_runner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCodeResponse) ProtoMessage() {}

func (x *RunCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_proto_runner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCodeResponse.ProtoReflect.Descriptor instead.
func (*RunCodeResponse) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_proto_runner_proto_rawDescGZIP(), []int{1}
}

func (x *RunCodeResponse) GetResults() []byte {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_internal_infrastructure_proto_runner_proto protoreflect.FileDescriptor

const file_internal_infrastructure_proto_runner_proto_rawDesc = "" +
	"\n" +
	"*internal/infrastructure/proto/runner.proto\x12\x06runner\"\x82\x01\n" +
	"\x0eRunCodeRequest\x12\x18\n" +
	"\astudent\x18\x01 \x01(\x05R\astudent\x12\x18\n" +
	"\aproblem\x18\x02 \x01(\x05R\aproblem\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x12\n" +
	"\x04lang\x18\x04 \x01(\tR\x04lang\x12\x14\n" +
	"\x05cases\x18\x05 \x01(\fR\x05cases\"+\n" +
	"\x0fRunCodeResponse\x12\x18\n" +
	"\aresults\x18\x01 \x01(\fR\aresults2D\n" +
	"\x06Runner\x12:\n" +
	"\aRunCode\x12\x16.runner.RunCodeRequest\x1a\x17.runner.RunCodeResponseB\n" +
	"Z\b.;runnerb\x06proto3"

var (
	file_internal_infrastructure_proto_runner_proto_rawDescOnce sync.Once
	file_internal_infrastructure_proto_runner_proto_rawDescData []byte
)

func file_internal_infrastructure_proto_runner_proto_rawDescGZIP() []byte {
	file_internal_infrastructure_proto_runner_proto_rawDescOnce.Do(func() {
		file_internal_infrastructure_proto_runner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_infrastructure_proto_runner_proto_rawDesc), len(file_internal_infrastructure_proto_runner_proto_rawDesc)))
	})
	return file_internal_infrastructure_proto_runner_proto_rawDescData
}

var file_internal_infrastructure_proto_runner_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_infrastructure_proto_runner_proto_goTypes = []any{
	(*RunCodeRequest)(nil),  // 0: runner.RunCodeRequest
	(*RunCodeResponse)(nil), // 1: runner.RunCodeResponse
}
var file_internal_infrastructure_proto_runner_proto_depIdxs = []int32{
	0, // 0: runner.Runner.RunCode:input_type -> runner.RunCodeRequest
	1, // 1: runner.Runner.RunCode:output_type -> runner.RunCodeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_infrastructure_proto_runner_proto_init() }
func file_internal_infrastructure_proto_runner_proto_init() {
	if File_internal_infrastructure_proto_runner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_infrastructure_proto_runner_proto_rawDesc), len(file_internal_infrastructure_proto_runner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_infrastructure_proto_runner_proto_goTypes,
		DependencyIndexes: file_internal_infrastructure_proto_runner_proto_depIdxs,
		MessageInfos:      file_internal_infrastructure_proto_runner_proto_msgTypes,
	}.Build()
	File_internal_infrastructure_proto_runner_proto = out.File
	file_internal_infrastructure_proto_runner_proto_goTypes = nil
	file_internal_infrastructure_proto_runner_proto_depIdxs = nil
}
